openapi: 3.0.0
info:
  version: '0.0.1'
  title: 'Ludo API apple group'
  description: 'All about ludo'
paths:
  /ludo:
    get:
      description: List of available Ludo games
      responses:
        '200':
          description: Successfully returned saved games
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: No games found    
    post:
      description: Create Game
      responses:
        '200':
          description: Successfully created game (method BeginGame started)
        '400':
          description: Unable to create game
          
  /ludo/{gameID}:
    get:
      description: Detailed information about the game
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: integer
          description: Enter the Game ID
      responses:
        '200':
          description: Successfully returned detailed information
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Players:
                      type: array
                      items:
                        type: object
        '400':
          description: Unable to return detailed information
    delete:
      description: Delete a game
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: integer
          description: Enter Game ID to delete
      responses:
        '200':
          description: Successfully deleted a game
        '400':
          description: Could not delete a game
    
  /ludo/{gameID}/players:  
    post:
      description: Send information on how many players will play the game
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: integer
        - name: nrOfPlayers
          in: query
          required: true
          description: Choose how many players in game 
          schema:
            type: integer
      responses:
        '200':
          description: Successfully sent number of players
        '400':
          description: Could not send number of players

  /ludo/{gameID}/players/{playerID}:
    get:
      description: Colors to chose from
      parameters:
      - name: gameID
        in: path
        required: true
        schema:
          type: integer
        description: Enter Game ID
      - name: playerID
        in: path
        required: true
        schema:
          type: integer
        description: Enter Player ID
      responses:
        '200':
          description: Successfully returned colors to choose from
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post: 
      description: Player choose Color
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: integer
          description: Enter Game ID
        - name: playerID
          in: path
          required: true
          schema:
            type: integer
          description: Enter Player ID
        - name: color
          in: query
          description: Player can choose color
          schema:
            type: integer
      responses:
        '200':
          description: Color selected Successfully
          
  /ludo/{gameID}/players/{playerID}/dice:
    get:
      description: Throw the dice
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: integer
          description: Enter Game ID
        - name: playerID
          in: path
          required: true
          schema:
            type: integer
          description: Enter Player ID
      responses:
        '200':
          description: Dice throwed successifully 
        '400':
          description: Unable to throw the dice