openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'LudoGame Api'
  description: 'desc'
paths:
  /ludo:
    get:
      description: List of available Ludo games
      responses:
        '200':
          description: Successfully returned saved games
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: No games found    
    post:
      description: Create a new game
      requestBody:
        description: Naming the started game
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: Successfully created a new game (method BeginGame started)
        '400':
          description: Unable to create a new game
          
  /ludo/{gameID}:
    get:
      description: Detailed information about the game
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully returned detailed information
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Players:
                      type: array
                      items:
                        type: object
        '400':
          description: Unable to return detailed information
    post:
      description: Start a saved game
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully started a saved game
    delete:
      description: Delete a game
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully deleted a game
        '400':
          description: Could not delete a game
    
  /ludo/{gameID}/players:  
    post:
      description: Send information on how many players will play the game
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully sent number of players
        '400':
          description: Could not send number of players

  /ludo/{gameID}/players/{playerID}:
    get:
      description: Colors to chose from
      parameters:
      - name: gameID
        in: path
        required: true
        schema:
          type: integer
      - name: playerID
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Successfully returned colors to choose from
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post: 
      description: Player choose Color
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: integer
        - name: playerID
          in: path
          required: true
          schema:
            type: integer
        - name: color
          in: query
          description: Allow player to choose color
          schema:
            type: integer
      responses:
        '200':
          description: Color selected Successfully
          
  /ludo/{gameID}/players/{playerID}/dice:
    get:
      description: Throw the dice
      parameters:
        - name: gameID
          in: path
          required: true
          schema:
            type: integer
        - name: playerID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Dice throwed successifully 
        '400':
          description: Unable to throw the dice