openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'LudoGame Api'
  description: 'All about Ludo!'
components:
  parameters:
    gameIDParameter:
      in: path
      name: gameID
      required: true
      schema:
        type: integer
    playerIDParameter:
      name: playerID
      in: path
      required: true
      schema:
        type: integer
    pieceIDParameter:
      name: pieceID
      in: path
      required: true
      schema:
        type: integer
paths:
  /ludo:
    get:
      description: List of available saved Ludo games
      responses:
        '200':
          description: Successfully returned saved games
          content:
            application/json: 
              schema:
                type: array
                items:
                  type: string
        '400':
          description: No games found    
    post:
      description: Create a new game
      responses:
        '200':
          description: Successfully created a new game
        '400':
          description: Unable to create a new game
          
  /ludo/{gameID}:
    parameters:
      - $ref: '#/components/parameters/gameIDParameter'
    get:
      description: Detailed information about the game
      responses:
        '200':
          description: Successfully returned detailed information
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Unable to return detailed information
    post:
      description: Start a saved game
      responses:
        '200':
          description: Successfully started a saved game
    delete:
      description: Delete a game
      responses:
        '200':
          description: Successfully deleted a game
        '400':
          description: Could not delete a game

  /ludo/{gameID}/save:
    parameters:
      - $ref: '#/components/parameters/gameIDParameter'
    get:
      description: Save a game
      responses:
        '200':
          description: Successfully saved the game
        '400':
          description: Unable to save game
    
  /ludo/{gameID}/players:  
    parameters:
      - $ref: '#/components/parameters/gameIDParameter'
    post:
      description: Create a new player with color
      responses:
        '200':
          description: Successfully created/added a player
        '400':
          description: Could not create/add a player
            
  /ludo/{gameID}/players/{playerID}/dice:
    get:
      description: Throw the dice and receive the value
      parameters:
        - $ref: '#/components/parameters/gameIDParameter'
        - $ref: '#/components/parameters/playerIDParameter'
      responses:
        '200':
          description: Dice throwed and returned value successfully 
        '400':
          description: Unable to throw the dice and return value
  /ludo/{gameID}/players/{playerID}/{pieceID}:
    post:
      description: Choose piece to move
      parameters:
        - $ref: '#/components/parameters/gameIDParameter'
        - $ref: '#/components/parameters/playerIDParameter'
        - $ref: '#/components/parameters/pieceIDParameter'
      responses:
        '200':
          description: Piece moved successfully
        '400':
          description: Could not move piece